### ISSUE TITLE
Bind comments to values according to indention

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/yaml_converter#1]
Seems that comments are binded to last parsed item in the tree, i.e.
```
# bid to head of root map
a: 
# bind to 'a' map
  b: 0
  # bind to 'b' key
  c: 1
  # bind to 'c' key
# bind to 'c'
x: 2
# bind to 'x' 
```

We should try to change this in ruamel.yaml, possibly through some setting of the parser. So that we can move values together with comments.
